Professors.delete_all
walker = Professors.create("pfirst_name" => "Russell ", "plast_name" => "Walker", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/walker_r.ashx")
cohen = Professors.create("pfirst_name" => "Jeff", "plast_name" => "Cohen", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Cohen_Jeff.ashx")
schoanthal = Professors.create("pfirst_name" => "David", "plast_name" => "Schoanthal", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Schonthal_David.ashx")
calkins = Professors.create("pfirst_name" => "Tim", "plast_name" => "Calkins", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/calkins_tim.ashx")
chopra = Professors.create("pfirst_name" => "Navin", "plast_name" => "Chopra", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Chopra_Navin.ashx")
finn = Professors.create("pfirst_name" => "Mark", "plast_name" => "Finn", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/finn_m.ashx")
brown = Professors.create("pfirst_name" => "Jen", "plast_name" => "Brown", "gender" => "F", "photo_url" => "http://www.kellogg.northwestern.edu/faculty/brown_j/htm/brownresearch_files/image002.png")
naughton = Professors.create("pfirst_name" => "James", "plast_name" => "Naughton", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Naughton_James.ashx")
furfine = Professors.create("pfirst_name" => "Craig", "plast_name" => "Furfine", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/furfine_c.ashx")
saraiya = Professors.create("pfirst_name" => "Chirag", "plast_name" => "Saraiya", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/saraiya_c.ashx")
braun = Professors.create("pfirst_name" => "Phillip", "plast_name" => "Braun", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/braun_phillip.ashx")
dranove = Professors.create("pfirst_name" => "David", "plast_name" => "Dranove", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/dranove_david.ashx")
uzzi = Professors.create("pfirst_name" => "Brian", "plast_name" => "Uzzi", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/uzzi_brian_2012.ashx")
garthwaite = Professors.create("pfirst_name" => "Craig", "plast_name" => "Garthwaite", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Garthwaite_Craig_2011.ashx")
hughes = Professors.create("pfirst_name" => "Edward F.X.", "plast_name" => "Hughes", "gender" => "M", "photo_url" => "http://www.kellogg.northwestern.edu/~/media/Images/faculty/headshot/Hughes_Edward13_RGB.ashx")

Classes.delete_all
hema914 = Classes.create("dept" => "HEMA", "class_no" => "914", "class_name" => "Biomedical Marketing")
mgmt441 = Classes.create("dept" => "MGMT", "class_no" => "441", "class_name" => "Intellectual Capital Management")
opns923 = Classes.create("dept" => "OPNS", "class_no" => "923", "class_name" => "Enterprise Risk Management")
kiei925 = Classes.create("dept" => "KIEI", "class_no" => "925", "class_name" => "Startup Programming and Management")
finc454 = Classes.create("dept" => "FINC", "class_no" => "454", "class_name" => "Real Estate Finance and Investments")
hema453 = Classes.create("dept" => "HEMA", "class_no" => "453", "class_name" => "Managerial Challenges in the Pharmaceutical, Biotech, and Medical Device Industries")
mecn430 = Classes.create("dept" => "MECN", "class_no" => "430", "class_name" => "Microeconomic Analysis")
intl473 = Classes.create("dept" => "INTL", "class_no" => "473", "class_name" => "Global Initiatives in Management")
acct430 = Classes.create("dept" => "ACCT", "class_no" => "430", "class_name" => "Accounting for Decision Making")
decs431 = Classes.create("dept" => "DECS", "class_no" => "431", "class_name" => "Business Analytics II")
finc440 = Classes.create("dept" => "FINC", "class_no" => "440", "class_name" => "Finance I/II")
mgmt431 = Classes.create("dept" => "MGMT", "class_no" => "431", "class_name" => "Business Strategy")
kiei462 = Classes.create("dept" => "KIEI", "class_no" => "462", "class_name" => "New Venture Discovery")
acct434 = Classes.create("dept" => "ACCT", "class_no" => "434", "class_name" => "Turbo Accounting")
finc940a = Classes.create("dept" => "FINC", "class_no" => "940-A", "class_name" => "Financial Modeling for Leveraged Buyout Transactions")
acct452 = Classes.create("dept" => "ACCT", "class_no" => "452", "class_name" => "Financial Reporting and Analysis II")


Link.delete_all
Link.create("prof_id" => walker.id, "class_id" => opns923.id)
Link.create("prof_id" => cohen.id, "class_id" => kiei925.id)
Link.create("prof_id" => schoanthal.id, "class_id" => kiei462.id)
Link.create("prof_id" => chopra.id, "class_id" => finc440.id)
Link.create("prof_id" => finn.id, "class_id" => acct434.id)
Link.create("prof_id" => finn.id, "class_id" => acct452.id)
Link.create("prof_id" => brown.id, "class_id" => mgmt431.id)
Link.create("prof_id" => naughton.id, "class_id" => acct430.id)
Link.create("prof_id" => furfine.id, "class_id" => finc454.id)
Link.create("prof_id" => saraiya.id, "class_id" => finc940a.id)
Link.create("prof_id" => braun.id, "class_id" => intl473.id)

